# Generated by Django 5.0.6 on 2024-06-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Project Manger'), ('dev', 'Developer')], default='dev', max_length=20),
        ),
    ]
